import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import LocalStorageService from '../../../services/LocalStorageService';
import ImageUpload from '../../common/ImageUpload';
import { ZONE_PLANS } from '../../../constants/plans';
import {
  FaPlus,
  FaEdit,
  FaTrash,
  FaLock,
  FaUnlock,
  FaSearch,
  FaCopy,
  FaStore,
  FaMapMarkerAlt,
  FaCheckCircle,
  FaTimesCircle,
  FaClock,
  FaCrown,
  FaTimes
} from 'react-icons/fa';
import SuperAdminLayout from '../SuperAdminLayout';

const ZoneAdvancedManagement = () => {
  const [zones, setZones] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [showForm, setShowForm] = useState(false);
  const [editingZone, setEditingZone] = useState(null);

  // Modal states
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [showCredentialsModal, setShowCredentialsModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [selectedZone, setSelectedZone] = useState(null);
  const [actionType, setActionType] = useState('');
  const [copiedField, setCopiedField] = useState(null);

  const [formData, setFormData] = useState({
    name: '',
    description: '',
    ownerName: '',
    ownerEmail: '',
    ownerPhone: '',
    address: '',
    city: '',
    state: '',
    zipCode: '',
    subscriptionPlan: 'premium', // Always premium for this component (like restaurant)
    status: 'active',
    password: '',
    logo: null,
    maxTables: null, // Unlimited for premium zones
    maxVendors: null, // Unlimited for premium zones
    paymentConfig: {
      upiId: '',
      paymentModel: 'shop-wise'
    }
  });

  // Password management state
  // Removed - Change Password functionality removed

  useEffect(() => {
    // Load Zone Advanced accounts from localStorage
    const loadZones = () => {
      const zones = LocalStorageService.getZones();
      // Filter only Zone Premium plan accounts
      const zonePremium = zones.filter(z => z.subscriptionPlan === 'premium');

      // For each zone, get the vendor count
      const zonesWithVendorCount = zonePremium.map(zone => {
        const vendors = LocalStorageService.getZoneVendors(zone.id);
        return {
          ...zone,
          vendorCount: vendors.length
        };
      });

      setZones(zonesWithVendorCount);
      setLoading(false);
    };

    loadZones();
  }, []);

  const filteredZones = zones.filter(zone => {
    const matchesSearch = zone.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      zone.ownerName.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || zone.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const handleSubmit = (e) => {
    e.preventDefault();

    if (!formData.password && !editingZone) {
      alert('Password is required for new zone accounts');
      return;
    }

    if (editingZone) {
      // Update existing zone
      const updateData = { ...formData };
      delete updateData.password;
      const updatedZone = LocalStorageService.updateZone(editingZone.id, updateData);
      if (updatedZone) {
        const updatedZones = zones.map(z =>
          z.id === editingZone.id ? updatedZone : z
        );
        setZones(updatedZones);
      }
    } else {
      // Create new Zone Advanced account
      const username = formData.name.toLowerCase().replace(/\s+/g, '_') + '_zone_admin';

      // Get the full subscription object for premium plan
      const premiumSubscription = ZONE_PLANS.premium;

      const zoneData = {
        ...formData,
        type: 'zone',
        subscriptionPlan: 'premium',
        subscription: premiumSubscription, // Include full subscription object
        slug: formData.name.toLowerCase().replace(/\s+/g, '-'),
        loginCredentials: {
          username: username,
          password: formData.password,
          lastLogin: null
        },
        tables: 0,
        revenue: '₹0',
        orders: 0,
        vendorCount: 0,
        lastActive: null,
        maxTables: formData.maxTables || null // null = unlimited for premium
      };

      const newZone = LocalStorageService.addZone(zoneData);
      setZones([...zones, { ...newZone, vendorCount: 0 }]);

      // Save credentials for zone_admin login with full subscription data
      LocalStorageService.saveShopCredentials({
        id: newZone.id,
        shopId: newZone.id, // Use the ID generated by addZone
        zoneId: newZone.id, // Assuming zoneId is the same as zone's ID
        name: newZone.name,
        shopName: newZone.name,
        ownerName: newZone.ownerName,
        ownerEmail: newZone.ownerEmail,
        ownerPhone: newZone.ownerPhone,
        loginCredentials: {
          username: username,
          password: formData.password,
        },
        type: 'zone_admin', // Crucial for authentication
        status: 'active', // Ensure it's active
        createdAt: newZone.createdAt || new Date().toISOString(),
        subscription: premiumSubscription, // Include full subscription object like restaurants
        subscriptionPlan: premiumSubscription.key
      });

      alert(`Zone Premium account created successfully!\n\nLogin Credentials:\nUsername: ${username}\nPassword: ${formData.password}\nPhone: ${formData.ownerPhone}\n\nThe client can now access full zone premium features.`);
    }

    resetForm();
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      ownerName: '',
      ownerEmail: '',
      ownerPhone: '',
      address: '',
      city: '',
      state: '',
      zipCode: '',
      subscriptionPlan: 'premium',
      status: 'active',
      password: '',
      logo: null,
      maxTables: null,
      maxVendors: null,
      paymentConfig: {
        upiId: '',
        paymentModel: 'shop-wise'
      }
    });
    setEditingZone(null);
    setShowForm(false);
  };

  const handleEdit = (zone) => {
    setFormData({
      name: zone.name,
      description: zone.description,
      ownerName: zone.ownerName,
      ownerEmail: zone.ownerEmail,
      ownerPhone: zone.ownerPhone,
      address: zone.address,
      city: zone.city,
      state: zone.state,
      zipCode: zone.zipCode,
      subscriptionPlan: zone.subscriptionPlan,
      status: zone.status,
      logo: zone.logo,
      maxTables: zone.maxTables || null,
      maxVendors: zone.maxVendors || null,
      paymentConfig: zone.paymentConfig || {
        upiId: '',
        paymentModel: 'shop-wise'
      }
    });
    setEditingZone(zone);
    setShowForm(true);
  };

  const handleDelete = (zoneId) => {
    const zone = zones.find(z => z.id === zoneId);
    if (zone) {
      setSelectedZone(zone);
      setShowDeleteModal(true);
    }
  };

  const confirmDelete = () => {
    if (selectedZone) {
      const success = LocalStorageService.deleteZone(selectedZone.id);
      if (success) {
        setZones(zones.filter(z => z.id !== selectedZone.id));
        LocalStorageService.deleteZoneVendors(selectedZone.id); // Also delete associated vendors
      }
    }
    setShowDeleteModal(false);
    setSelectedZone(null);
  };

  const toggleStatus = (zoneId) => {
    const zone = zones.find(z => z.id === zoneId);
    if (zone) {
      setSelectedZone(zone);
      setActionType(zone.status === 'active' ? 'suspend' : 'activate');
      setShowConfirmModal(true);
    }
  };

  const confirmStatusChange = () => {
    if (selectedZone) {
      const newStatus = selectedZone.status === 'active' ? 'suspended' : 'active';
      const updatedZone = LocalStorageService.updateZone(selectedZone.id, { status: newStatus });
      if (updatedZone) {
        setZones(zones.map(z =>
          z.id === selectedZone.id ? updatedZone : z
        ));
      }
    }
    setShowConfirmModal(false);
    setSelectedZone(null);
    setActionType('');
  };

  const copyCredentials = (zone) => {
    setSelectedZone(zone);
    setShowCredentialsModal(true);
    setCopiedField(null); // Reset copied field when opening modal
  };

  const handleCopyToClipboard = () => {
    if (!selectedZone) return;
    
    const username = selectedZone.loginCredentials?.username || 
                    selectedZone.name.toLowerCase().replace(/\s+/g, '_') + '_zone_admin';
    const password = selectedZone.loginCredentials?.password || 'N/A';
    
    const credentials = `Premium Zone Credentials:

Zone: ${selectedZone.name}
Owner: ${selectedZone.ownerName}
Email: ${selectedZone.ownerEmail}
Phone: ${selectedZone.ownerPhone}

Login Details:
Username: ${username}
Password: ${password}
Login URL: ${window.location.origin}/tableserve/login

Plan: Premium
Max Tables: ${selectedZone.maxTables || 'Unlimited'}
Max Vendors: ${selectedZone.maxVendors || 'Unlimited'}
Status: ${selectedZone.status}`;
    
    navigator.clipboard.writeText(credentials).then(() => {
      setShowCredentialsModal(false);
      setSelectedZone(null);
    }).catch(() => {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = credentials;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setShowCredentialsModal(false);
      setSelectedZone(null);
    });
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'active': return 'status-success bg-green-500/20';
      case 'suspended': return 'status-error bg-red-500/20';
      case 'pending': return 'status-warning bg-yellow-500/20';
      default: return 'text-theme-text-tertiary bg-gray-500/20';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'active': return <FaCheckCircle />;
      case 'suspended': return <FaTimesCircle />;
      case 'pending': return <FaClock />;
      default: return <FaClock />;
    }
  };

  if (loading) {
    return (
      <SuperAdminLayout>
        <div className="flex items-center justify-center h-96">
          <div className="text-center">
            <div className="w-16 h-16 spinner-theme rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-theme-text-primary font-raleway">Loading Premium Zone accounts...</p>
          </div>
        </div>
      </SuperAdminLayout>
    );
  }

  return (
    <SuperAdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center space-y-4 sm:space-y-0">
          <div>
            <h1 className="text-2xl sm:text-3xl font-fredoka text-theme-text-primary mb-2 flex items-center">
              <FaCrown className="mr-3 text-orange-500" />
              Premium Zone Management
            </h1>
            <p className="text-theme-text-secondary font-raleway text-sm sm:text-base">Create and manage Premium Zone plan accounts with unlimited vendors and tables.</p>
          </div>
          <button
            onClick={() => setShowForm(true)}
            className="w-full sm:w-auto btn-primary px-4 py-2 rounded-lg font-raleway font-semibold flex items-center justify-center space-x-2"
          >
            <FaPlus />
            <span>Create Premium Zone</span>
          </button>
        </div>

        {/* Filters and Search */}
        <div className="admin-card rounded-2xl p-4 sm:p-6">
          <div className="flex flex-col space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center space-y-4 sm:space-y-0 sm:space-x-4">
              <div className="relative flex-1">
                <FaSearch className="absolute left-3 top-1/2 transform -translate-y-1/2 text-theme-text-tertiary" />
                <input
                  type="text"
                  placeholder="Search zones..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="w-full input-theme rounded-lg pl-10 pr-4 py-2 focus:outline-none"
                />
              </div>
              <select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="w-full sm:w-auto input-theme rounded-lg px-4 py-2 focus:outline-none"
              >
                <option value="all">All Status</option>
                <option value="active">Active</option>
                <option value="suspended">Suspended</option>
                <option value="pending">Pending</option>
              </select>
            </div>
          </div>
        </div>

        {/* Statistics */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 sm:gap-6">
          <div className="admin-card rounded-2xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-theme-text-secondary font-raleway text-sm">Total Zones</p>
                <p className="text-2xl font-sans text-theme-text-primary">{zones.length}</p>
              </div>
              <FaStore className="text-3xl text-theme-accent-primary" />
            </div>
          </div>
          <div className="admin-card rounded-2xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-theme-text-secondary font-raleway text-sm">Active</p>
                <p className="text-2xl font-sans text-status-success">
                  {zones.filter(z => z.status === 'active').length}
                </p>
              </div>
              <FaCheckCircle className="text-3xl text-status-success" />
            </div>
          </div>
          <div className="admin-card rounded-2xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-theme-text-secondary font-raleway text-sm">Total Vendors</p>
                <p className="text-2xl font-sans text-theme-text-primary">
                  {zones.reduce((sum, z) => sum + (z.vendorCount || 0), 0)}
                </p>
              </div>
              <FaMapMarkerAlt className="text-3xl text-theme-accent-primary" />
            </div>
          </div>
          <div className="admin-card rounded-2xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-theme-text-secondary font-raleway text-sm">Total Revenue</p>
                <p className="text-2xl font-sans text-status-success">
                  ₹{zones.reduce((sum, z) => sum + parseInt(z.revenue?.replace('₹', '').replace(',', '') || '0'), 0).toLocaleString('en-IN')}
                </p>
              </div>
              <FaCheckCircle className="text-3xl text-status-success" />
            </div>
          </div>
        </div>

        {/* Zone Advanced Accounts List */}
        <div className="admin-card rounded-2xl p-4">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-theme-bg-hover">
                <tr>
                  <th className="text-left p-4 text-theme-text-secondary font-raleway font-semibold">Zone</th>
                  <th className="text-left p-4 text-theme-text-secondary font-raleway font-semibold">Owner</th>
                  <th className="text-left p-4 text-theme-text-secondary font-raleway font-semibold">Contact</th>
                  <th className="text-left p-4 text-theme-text-secondary font-raleway font-semibold">Status</th>
                  <th className="text-left p-4 text-theme-text-secondary font-raleway font-semibold">Performance</th>
                  <th className="text-left p-4 text-theme-text-secondary font-raleway font-semibold">Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredZones.map((zone, index) => (
                  <motion.tr
                    key={`zone-${zone.id}-${index}`}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="border-t border-theme-border-primary hover:bg-theme-bg-hover transition-colors"
                  >
                    <td className="p-4">
                      <div className="flex items-center space-x-3">
                        <img
                          src={zone.logo || '/api/placeholder/40/40'}
                          alt={zone.name}
                          className="w-10 h-10 rounded-lg object-cover"
                        />
                        <div>
                          <h4 className="text-theme-text-primary font-raleway font-medium">{zone.name}</h4>
                          <p className="text-theme-text-secondary font-raleway text-sm">Zone Premium</p>
                        </div>
                      </div>
                    </td>
                    <td className="p-4">
                      <div>
                        <p className="text-theme-text-primary font-raleway">{zone.ownerName}</p>
                        <p className="text-theme-text-secondary font-raleway text-sm">{zone.city}, {zone.state}</p>
                      </div>
                    </td>
                    <td className="p-4">
                      <div>
                        <p className="text-theme-text-secondary font-raleway text-sm">{zone.ownerPhone}</p>
                        <p className="text-theme-text-secondary font-raleway text-sm">{zone.ownerEmail}</p>
                      </div>
                    </td>
                    <td className="p-4">
                      <div className={`inline-flex items-center space-x-2 px-3 py-1 rounded-full text-sm font-raleway ${getStatusColor(zone.status)}`}>
                        {getStatusIcon(zone.status)}
                        <span className="capitalize">{zone.status}</span>
                      </div>
                    </td>
                    <td className="p-4">
                      <div>
                        <p className="text-theme-text-primary font-sans font-medium">{zone.revenue}</p>
                        <p className="text-theme-text-secondary font-raleway text-sm">{zone.vendorCount || 0} vendors • {zone.tables || 0} tables</p>
                      </div>
                    </td>
                    <td className="p-4">
                      <div className="flex items-center space-x-2">
                        <button
                          onClick={() => handleEdit(zone)}
                          className="text-status-info hover:text-status-info/80 p-2 rounded-lg hover:bg-status-info/20 transition-colors"
                          title="Edit Zone"
                        >
                          <FaEdit />
                        </button>
                        <button
                          onClick={() => toggleStatus(zone.id)}
                          className={`p-2 rounded-lg transition-colors ${zone.status === 'active'
                            ? 'text-status-error hover:text-status-error/80 hover:bg-status-error/20'
                            : 'text-status-success hover:text-status-success/80 hover:bg-status-success/20'
                            }`}
                          title={zone.status === 'active' ? 'Suspend Account' : 'Activate Account'}
                        >
                          {zone.status === 'active' ? <FaLock /> : <FaUnlock />}
                        </button>
                        <button
                          onClick={() => copyCredentials(zone)}
                          className="text-status-success hover:text-status-success/80 p-2 rounded-lg hover:bg-status-success/20 transition-colors"
                          title="Copy Credentials"
                        >
                          <FaCopy />
                        </button>
                        <button
                          onClick={() => handleDelete(zone.id)}
                          className="text-status-error hover:text-status-error/80 p-2 rounded-lg hover:bg-status-error/20 transition-colors"
                          title="Delete Zone"
                        >
                          <FaTrash />
                        </button>
                      </div>
                    </td>
                  </motion.tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Empty State */}
          {filteredZones.length === 0 && (
            <div className="text-center py-12">
              <FaStore className="text-6xl text-theme-text-tertiary mx-auto mb-4" />
              <h3 className="text-xl font-fredoka text-theme-text-primary mb-2">
                {zones.length === 0 ? 'No Zone Advanced Accounts Yet' : 'No Zones Found'}
              </h3>
              <p className="text-theme-text-secondary font-raleway mb-4">
                {zones.length === 0
                  ? 'Create Zone Advanced accounts for clients who need full zone management features'
                  : 'No zones match your current search criteria'
                }
              </p>
              {zones.length === 0 && (
                <button
                  onClick={() => setShowForm(true)}
                  className="btn-primary px-6 py-3 rounded-lg font-raleway font-semibold"
                >
                  Create First Zone Advanced Account
                </button>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Add/Edit Form Modal */}
      <AnimatePresence>
        {showForm && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="admin-card rounded-2xl p-6 w-full max-w-4xl max-h-[90vh] overflow-y-auto"
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-fredoka text-theme-text-primary flex items-center">
                  <FaCrown className="mr-3 text-orange-500" />
                  {editingZone ? 'Edit Premium Zone' : 'Create Premium Zone'}
                </h2>
                <button
                  onClick={resetForm}
                  className="text-theme-text-secondary hover:text-theme-text-primary transition-colors p-2"
                >
                  <FaTimes className="text-xl" />
                </button>
              </div>

              <form onSubmit={handleSubmit} className="space-y-6">
                {/* Basic Information */}
                <div className="space-y-4">
                  <h3 className="text-xl font-fredoka text-theme-text-primary border-b border-theme-border-primary pb-2">
                    Basic Information
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Zone Name *</label>
                      <input
                        type="text"
                        value={formData.name}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="Enter zone name"
                        required
                      />
                    </div>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Zone Type</label>
                      <input
                        type="text"
                        value="Food Zone"
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="Food Zone"
                        disabled
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-theme-text-primary font-raleway mb-2 text-base">Description</label>
                    <textarea
                      value={formData.description}
                      onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                      className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                      placeholder="Brief description of the zone"
                      rows="3"
                    />
                  </div>
                </div>

                {/* Owner Information */}
                <div className="space-y-4">
                  <h3 className="text-xl font-fredoka text-theme-text-primary border-b border-theme-border-primary pb-2">
                    Owner Information
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Owner Name *</label>
                      <input
                        type="text"
                        value={formData.ownerName}
                        onChange={(e) => setFormData({ ...formData, ownerName: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="Enter owner full name"
                        required
                      />
                    </div>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Owner Email *</label>
                      <input
                        type="email"
                        value={formData.ownerEmail}
                        onChange={(e) => setFormData({ ...formData, ownerEmail: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="owner@zone.com"
                        required
                      />
                    </div>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Owner Phone *</label>
                      <input
                        type="tel"
                        value={formData.ownerPhone}
                        onChange={(e) => setFormData({ ...formData, ownerPhone: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="+91 98765 43210"
                        required
                      />
                    </div>
                  </div>
                </div>

                {/* Location Information */}
                <div className="space-y-4">
                  <h3 className="text-xl font-fredoka text-theme-text-primary border-b border-theme-border-primary pb-2">
                    Location Information
                  </h3>
                  <div>
                    <label className="block text-theme-text-primary font-raleway mb-2 text-base">Address</label>
                    <input
                      type="text"
                      value={formData.address}
                      onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                      className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                      placeholder="Street address"
                    />
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">City</label>
                      <input
                        type="text"
                        value={formData.city}
                        onChange={(e) => setFormData({ ...formData, city: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="City"
                      />
                    </div>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">State</label>
                      <input
                        type="text"
                        value={formData.state}
                        onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="State"
                      />
                    </div>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">ZIP Code</label>
                      <input
                        type="text"
                        value={formData.zipCode}
                        onChange={(e) => setFormData({ ...formData, zipCode: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="ZIP Code"
                      />
                    </div>
                  </div>
                </div>

                {/* Premium Configuration */}
                <div className="space-y-4">
                  <h3 className="text-xl font-fredoka text-orange-600 border-b border-orange-200 pb-2 flex items-center">
                    <FaCrown className="mr-2" />
                    Premium Configuration
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Maximum Tables</label>
                      <input
                        type="number"
                        value={formData.maxTables || ''}
                        onChange={(e) => setFormData({ ...formData, maxTables: e.target.value ? parseInt(e.target.value) || null : null })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="Leave blank for unlimited tables"
                        min="1"
                      />
                      <p className="text-theme-text-tertiary text-base mt-1">Leave blank for unlimited tables (Premium feature)</p>
                    </div>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Maximum Vendors</label>
                      <input
                        type="number"
                        value={formData.maxVendors || ''}
                        onChange={(e) => setFormData({ ...formData, maxVendors: e.target.value ? parseInt(e.target.value) || null : null })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="Leave blank for unlimited vendors"
                        min="1"
                      />
                      <p className="text-theme-text-tertiary text-base mt-1">Leave blank for unlimited vendors (Premium feature)</p>
                    </div>
                  </div>
                </div>

                {/* Login Credentials */}
                {!editingZone && (
                  <div className="space-y-4">
                    <h3 className="text-xl font-fredoka text-theme-text-primary border-b border-theme-border-primary pb-2">
                      Login Credentials
                    </h3>
                    <div>
                      <label className="block text-theme-text-primary font-raleway mb-2 text-base">Login Password *</label>
                      <input
                        type="password"
                        value={formData.password}
                        onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                        className="input-theme autofill-protected rounded-lg px-4 py-2 w-full focus:outline-none"
                        placeholder="Enter secure password for zone admin login"
                        required
                        minLength="6"
                      />
                      <p className="text-theme-text-tertiary text-base mt-1">This password will be used for zone admin login</p>
                    </div>
                  </div>
                )}



                {/* Form Actions */}
                <div className="flex justify-end space-x-4 pt-6 border-t border-theme-border-primary">
                  <button
                    type="button"
                    onClick={resetForm}
                    className="px-6 py-2 text-theme-text-secondary rounded-lg font-raleway font-semibold hover:text-theme-text-primary transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-2 rounded-lg font-raleway font-semibold transition-colors"
                  >
                    {editingZone ? 'Update Premium Zone' : 'Create Premium Zone'}
                  </button>
                </div>
              </form>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Confirmation Modal */}
      <AnimatePresence>
        {showConfirmModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="admin-card rounded-2xl p-6 w-full max-w-md"
            >
              <div className="text-center">
                <div className="w-16 h-16 mx-auto mb-4 bg-orange-100 rounded-full flex items-center justify-center">
                  {actionType === 'suspend' ? (
                    <FaTimesCircle className="text-3xl text-orange-500" />
                  ) : (
                    <FaCheckCircle className="text-3xl text-orange-500" />
                  )}
                </div>
                <h3 className="text-xl font-fredoka text-theme-text-primary mb-2">
                  {actionType === 'suspend' ? 'Suspend Zone' : 'Activate Zone'}
                </h3>
                <p className="text-theme-text-secondary font-raleway mb-6">
                  Are you sure you want to {actionType} <span className="font-semibold">{selectedZone?.name}</span>?
                  {actionType === 'suspend' && ' This will prevent the zone admin from accessing the system.'}
                </p>
                <div className="flex space-x-4">
                  <button
                    onClick={() => {
                      setShowConfirmModal(false);
                      setSelectedZone(null);
                      setActionType('');
                    }}
                    className="flex-1 px-4 py-2 text-theme-text-secondary border border-theme-border-primary rounded-lg font-raleway hover:text-theme-text-primary transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={confirmStatusChange}
                    className="flex-1 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg font-raleway font-semibold transition-colors"
                  >
                    {actionType === 'suspend' ? 'Suspend' : 'Activate'}
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Credentials Modal */}
      <AnimatePresence>
        {showCredentialsModal && selectedZone && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-gradient-to-br from-orange-900/20 via-black/40 to-orange-900/20 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="admin-card rounded-2xl p-6 w-full max-w-2xl max-h-[85vh] overflow-y-auto"
            >
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-fredoka text-theme-text-primary flex items-center">
                  <FaCrown className="mr-2 text-orange-500" />
                  Premium Zone Credentials
                </h3>
                <button
                  onClick={() => {
                    setShowCredentialsModal(false);
                    setSelectedZone(null);
                  }}
                  className="text-theme-text-secondary hover:text-theme-text-primary transition-colors p-2"
                >
                  <FaTimes className="text-xl" />
                </button>
              </div>

              <div className="space-y-6">
                {/* Zone Details */}
                <div className="bg-orange-50 rounded-lg p-3">
                  <h4 className="font-fredoka text-orange-600 mb-2 text-base">Zone Information</h4>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                    <div>
                      <span className="text-theme-text-secondary text-sm">Zone:</span>
                      <p className="font-semibold text-theme-text-primary text-base">{selectedZone.name}</p>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm">Owner:</span>
                      <p className="font-semibold text-theme-text-primary text-base">{selectedZone.ownerName}</p>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm">Email:</span>
                      <p className="font-semibold text-theme-text-primary text-base">{selectedZone.ownerEmail}</p>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm">Phone:</span>
                      <p className="font-semibold text-theme-text-primary text-base">{selectedZone.ownerPhone}</p>
                    </div>
                  </div>
                </div>

                {/* Login Credentials */}
                <div className="bg-orange-50 rounded-lg p-4">
                  <h4 className="font-fredoka text-orange-600 mb-3 text-base">Login Credentials</h4>
                  <div className="space-y-3">
                    <div>
                      <span className="text-theme-text-secondary text-sm mb-1 block">Username:</span>
                      <div className="flex items-center space-x-2">
                        <p className="font-mono bg-white p-2 rounded border text-theme-text-primary text-base flex-1">
                          {selectedZone.loginCredentials?.username || 
                           selectedZone.name.toLowerCase().replace(/\s+/g, '_') + '_zone_admin'}
                        </p>
                        <button
                          onClick={() => {
                            const username = selectedZone.loginCredentials?.username || 
                                           selectedZone.name.toLowerCase().replace(/\s+/g, '_') + '_zone_admin';
                            navigator.clipboard.writeText(username).then(() => {
                              setCopiedField('username');
                              setTimeout(() => setCopiedField(null), 2000);
                            }).catch(() => {
                              const textArea = document.createElement('textarea');
                              textArea.value = username;
                              document.body.appendChild(textArea);
                              textArea.select();
                              document.execCommand('copy');
                              document.body.removeChild(textArea);
                              setCopiedField('username');
                              setTimeout(() => setCopiedField(null), 2000);
                            });
                          }}
                          className={`p-1.5 rounded transition-colors ${
                            copiedField === 'username' 
                              ? 'text-green-600 bg-green-50 hover:text-green-700 hover:bg-green-100' 
                              : 'text-orange-500 hover:text-orange-600 hover:bg-orange-50'
                          }`}
                          title={copiedField === 'username' ? 'Copied!' : 'Copy Username'}
                        >
                          <FaCopy className="text-xs" />
                        </button>
                      </div>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm mb-1 block">Password:</span>
                      <div className="flex items-center space-x-2">
                        <p className="font-mono bg-white p-2 rounded border text-theme-text-primary text-base flex-1">
                          {selectedZone.loginCredentials?.password || 'N/A'}
                        </p>
                        <button
                          onClick={() => {
                            const password = selectedZone.loginCredentials?.password || 'N/A';
                            navigator.clipboard.writeText(password).then(() => {
                              setCopiedField('password');
                              setTimeout(() => setCopiedField(null), 2000);
                            }).catch(() => {
                              const textArea = document.createElement('textarea');
                              textArea.value = password;
                              document.body.appendChild(textArea);
                              textArea.select();
                              document.execCommand('copy');
                              document.body.removeChild(textArea);
                              setCopiedField('password');
                              setTimeout(() => setCopiedField(null), 2000);
                            });
                          }}
                          className={`p-1.5 rounded transition-colors ${
                            copiedField === 'password' 
                              ? 'text-green-600 bg-green-50 hover:text-green-700 hover:bg-green-100' 
                              : 'text-orange-500 hover:text-orange-600 hover:bg-orange-50'
                          }`}
                          title={copiedField === 'password' ? 'Copied!' : 'Copy Password'}
                        >
                          <FaCopy className="text-xs" />
                        </button>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Premium Details */}
                <div className="bg-orange-50 rounded-lg p-3">
                  <h4 className="font-fredoka text-orange-600 mb-2 text-base">Premium Plan Details</h4>
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-sm">
                    <div>
                      <span className="text-theme-text-secondary text-sm">Plan:</span>
                      <p className="font-semibold text-orange-600 text-base">Premium</p>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm">Max Tables:</span>
                      <p className="font-semibold text-theme-text-primary text-base">{selectedZone.maxTables || 'Unlimited'}</p>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm">Max Vendors:</span>
                      <p className="font-semibold text-theme-text-primary text-base">{selectedZone.maxVendors || 'Unlimited'}</p>
                    </div>
                    <div>
                      <span className="text-theme-text-secondary text-sm">Status:</span>
                      <p className={`font-semibold text-base ${
                        selectedZone.status === 'active' ? 'text-green-600' :
                        selectedZone.status === 'suspended' ? 'text-red-600' : 'text-yellow-600'
                      }`}>
                        {selectedZone.status?.charAt(0).toUpperCase() + selectedZone.status?.slice(1)}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="flex justify-end space-x-4 mt-6 pt-6 border-t border-theme-border-primary">
                <button
                  onClick={() => {
                    setShowCredentialsModal(false);
                    setSelectedZone(null);
                  }}
                  className="px-6 py-2 text-theme-text-secondary border border-theme-border-primary rounded-lg font-raleway hover:text-theme-text-primary transition-colors"
                >
                  Close
                </button>
                <button
                  onClick={handleCopyToClipboard}
                  className="px-6 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg font-raleway font-semibold flex items-center space-x-2 transition-colors"
                >
                  <FaCopy />
                  <span>Copy All Credentials</span>
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Delete Modal */}
      <AnimatePresence>
        {showDeleteModal && selectedZone && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="admin-card rounded-2xl p-6 w-full max-w-md"
            >
              <div className="text-center">
                <div className="w-16 h-16 mx-auto mb-4 bg-red-100 rounded-full flex items-center justify-center">
                  <FaTrash className="text-3xl text-red-500" />
                </div>
                <h3 className="text-xl font-fredoka text-theme-text-primary mb-2">
                  Delete Premium Zone
                </h3>
                <p className="text-theme-text-secondary font-raleway mb-2">
                  Are you sure you want to permanently delete
                </p>
                <p className="font-semibold text-theme-text-primary mb-4">
                  {selectedZone.name}?
                </p>
                <div className="bg-red-50 border border-red-200 rounded-lg p-3 mb-6">
                  <p className="text-red-600 text-sm font-medium">
                    ⚠️ This action cannot be undone. All zone data, vendors, orders, and QR codes will be permanently lost.
                  </p>
                </div>
                <div className="flex space-x-4">
                  <button
                    onClick={() => {
                      setShowDeleteModal(false);
                      setSelectedZone(null);
                    }}
                    className="flex-1 px-4 py-2 text-theme-text-secondary border border-theme-border-primary rounded-lg font-raleway hover:text-theme-text-primary transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={confirmDelete}
                    className="flex-1 px-4 py-2 bg-red-500 hover:bg-red-600 text-white rounded-lg font-raleway font-semibold transition-colors"
                  >
                    Delete Permanently
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </SuperAdminLayout>
  );
};

export default ZoneAdvancedManagement;
